spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      static-path-pattern: /**
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/middleSchool?serverTimezone=CTT
    username: root
    password: root
    name: middleSchool

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.school.result.pojo #实体类“类型别名包”

server:
  port: 8899
