spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
      static-path-pattern: /**
  thymeleaf:
    cache: false
  #      prefix: classpath:/templates/
  #      suffix: .html

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/middleSchool?serverTimezone=CTT
    username: root
    password: root
    name: middleSchool

  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
#  devtools:
#    restart: true

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.school.result.mapper

server:
  port: 8899

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.school.result.pojo,com.school.result.vo #实体类“类型别名包”
#  configuration:
#    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl